@startuml
'https://plantuml.com/sequence-diagram
autonumber
skinparam responseMessageBelowArrow true
participant ConfigurationClassPostProcessor.postProcessBeanFactory as processor
participant ConfigurationClassParser.processConfigurationClass as parser
participant ConfigurationClassParser.processImport as import
participant ConfigurationClassBeanDefinitionReader.loadBeanDefinitions as reader
activate processor
processor->parser:解析元信息
parser->parser:解析configuration
parser->import:解析import
import->import:递归获取到import的configuration
import->import:3.1中加入对ImportSelector和ImportBeanDefinitionRegistrar的直接实例化以及调用获取结果
import->parser:递归调用parser对configuration进行元注解解析
parser->processor:返回Configuration的ConfigurationClass
processor->reader:处理configuration
reader->reader:将Configuration注册到spring容器中
reader->reader:处理@Import、@ImportResource、@Bean相关的Bean并注册到容器中
reader->processor:处理完毕
@enduml